#!/bin/env bash
# source functions

function confirm() {
  printf "\e[32mOK\e[0m\n"
}
function missing() {
  printf "\x1b[38;5;214mMISSING\e[0m\n"
}
# Variabili Colori
export green='\e[32m'
export blue='\x1b[38;5;81m'
export orange='\x1b[38;5;214m'
export red='\033[0;31m'
export clear='\e[0m'
export bold_in='\033[1m'
export bold_out='\033[0m'
export title_script="Markchad configuration installation"
export msg_nv_exe="Required executable control"
export intro_script="The script was created and tested on a Rocky Linux 8.4 system. Consequently, all commands refer to a RHEL based system, especially the commands for installing the required packages, in case you are using another Linux distribution, you should adapt them to your own distribution."
export nv_check_title="Neovim availability check"
export nv_check_ok="Executable detected"
export nv_check_no="No Neovim executable was found to be available on the system in use, the configuration requires an installation of Neovim 0.10.0 or higher. For its installation, reference can be made to the official documentation available in the links below."
export warning="WARNING"
# function nv_check_no() {
#   printf "${red}%s${clear} No Neovim (${orange}%s${clear}) executable was found to be available on the system in use,\n the configuration requires an installation of Neovim 0.10.0 or higher.\n\n For its installation, reference can be made to the official documentation\n available in the links below.\n\n" "WARNING" "nvim" | indent 4
# }
function nv_outdated() {
printf "\n${red}%s${clear} detected incompatible version of Neovim:\n\n\tVersion required ${blue}%s${clear}\n\tVersion installed ${orange}%s${clear}\n\n" "WARNING" "$nv_req" "$nv_strip" | indent 4
}
function nv_outdated_info(){
printf "The installed version ${orange}%s${clear} does not meet the minimum\nrequirements for a successful installation it is recommended\nto run an update of Neovim.\n\n" "$nv_vers" | indent 2
}
function official_doc() {
  printf " ${bold_in}%s\n${bold_out}" "Official documentation" | indent 2
  printf " https://github.com/neovim/neovim/blob/master/INSTALL.md\n" | indent 3
  printf " https://github.com/neovim/neovim/blob/master/BUILD.md\n\n" | indent 3
  printf " ${bold_in}%s\n\n${bold_out}" "Installation halted pending availability of minimum requirements." | indent 1
}
# Messaggi Vari
function info_to_exit() {
  printf "Press any key to terminate the script...\n" | indent  6
}
